### ISSUE TITLE
when try to click on Export to Excel Button ,an Exception error appeared , and when try to reselect Exporting path and click again ,file exported

### ISSUE THREAD

**Issue by emannabil123** [emannabil123/repository01#1]
************** Exception Text **************
System.Exception: ExportToExcel: 
ExportToExcel: Excel file could not be saved! Check filepath.
Could not find a part of the path 'c:\exports\Item.xls'.
   at Microtech.Infinity6.DataIntegratin.Presentation.ServiceGateway.ExportToExcel(DataTable Tbl, String ExcelFilePath) in C:\Users\mustafa\source\repos\MicrotechInfinity6\Microtech.Infinity6.DataIntegratin.Presentation\ServiceGateway.cs:line 656
   at TestApp.LocalAndSftp.button3_Click(Object sender, EventArgs e) in C:\Users\mustafa\source\repos\MicrotechInfinity6\TestApp\LocalAndSftp.cs:line 144
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
![2](https://user-images.githubusercontent.com/76688488/103369962-348b5200-4ad4-11eb-9e4a-67ab0a34f101.jpg)

**Comment by MustafaE-ext** [comment]
not a bug
