### ISSUE TITLE
When select the same index file path and txt file path in SFTP , display this message ...why??

### ISSUE THREAD

**Issue by emannabil123** [emannabil123/repository01#6]
Note : I mapping this in Local and mapping success

**log details:**
2021-01-04 11:53:04,688 [1] INFO  TestApp.LocalAndSftp [(null)] - System.Data.OleDb.OleDbException (0x80004005): External table is not in the expected format.
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDb
![when select the same path that try it on local and succes map](https://user-images.githubusercontent.com/76688488/103523411-77f31100-4e84-11eb-86b0-bd92f27e69df.PNG)
ConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at IndexFileMapper.ExcelFileReader.CreateDataTable() in C:\Users\mustafa\source\repos\MicrotechInfinity6\IndexFileMapper\ExcelFileReader.cs:line 22
   at IndexFileMapper.ToshibaIndexFileMapper.MapEntities() in C:\Users\mustafa\source\repos\MicrotechInfinity6\IndexFileMapper\ToshibaIndexFileMapper.cs:line 48
   at TestApp.LocalAndSftp.button1_Click(Object sender, EventArgs e) in C:\Users\mustafa\source\repos\MicrotechInfinity6\TestApp\LocalAndSftp.cs:line 54

**Comment by emannabil123** [comment]
[IndexFile.xlsx](https://github.com/emannabil123/repository01/files/5764101/IndexFile.xlsx)
[Stock_Card_NRF -2.txt](https://github.com/emannabil123/repository01/files/5764102/Stock_Card_NRF.-2.txt)

**Comment by MustafaE-ext** [comment]
not a bug tinysftpserver conf
